version: 3.2.{build}
os: Visual Studio 2017
clone_depth: 2
configuration: Release

pull_requests:
  do_not_increment_build_number: true
  
init: 
  - git config --global core.autocrlf input
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - ps: If ("$env:APPVEYOR_REPO_TAG" -ne "true") { $env:VERSION_SUFFIX="pre" }
  - ps: 'Write-Output "Version: $($env:APPVEYOR_BUILD_VERSION)-$($env:VERSION_SUFFIX)"'

install:
  - cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
  - cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log

before_build:
  - ps: .\build\Set-BuildVersion -Version $env:APPVEYOR_BUILD_VERSION -Suffix $env:VERSION_SUFFIX
  - nuget sources add -name Exceptionless -source https://www.myget.org/F/exceptionless/api/v3/index.json
  - appveyor-retry dotnet restore -v Minimal

build_script: 
  - dotnet build -c Release

#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - ps: Push-Location .\test\Exceptionless.DateTimeExtensions.Tests
  - ps: dotnet xunit -configuration Release

after_test:
  - dotnet pack -c Release

artifacts:
  - path: artifacts\*.nupkg
    name: NuGet
 
deploy:
  - provider: Environment
    name: MyGet
  - provider: Environment
    name: NuGet
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    auth_token:
      secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
    draft: true
    on:
      appveyor_repo_tag: true
      
notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: PigIGGo7UUDwdb0KGM/s7OfpAng/OMJx7q33jKfzudFBiXi1EBEd0DRmkbCc7CiX
