name: Build
on: [push, pull_request]

jobs:
  build:
    uses: FoundatioFx/Foundatio/.github/workflows/build-workflow.yml@main
    with:
        org: exceptionless
        new-test-runner: true
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
      FEEDZ_KEY: ${{ secrets.FEEDZ_KEY }}
